return{
	--mythic
	["Conqueror"]="King's Justice",
	["Glanzfaust"]="Ascetic's Fury",
	["Yagrush"]="Mystic Boon",
	["Laevateinn"]="Vidohunir",
	["Murgleis"]="Death Blossom",
	["Vajra"]="Mandalic Stab",
	["Burtgang"]="Atonement",
	["Liberator"]="Insurgency",
	["Aymur"]="Primal Rend",
	["Carnwenhan"]="Mordant Rime",
	["Gastraphetes"]="Trueflight",
	["Kogarasumaru"]="Tachi: Rana",
	["Nagi"]="Blade: Kamu",
	["Ryunohige"]="Drakesbane",
	["Nirvana"]="Garland of Bliss",
	["Tizona"]="Expiacion",
	["Death Penalty"]="Leaden Salute",
	["Kenkonken"]="Stringing Pummel",
	["Terpsichore"]="Pyrrhic Kleos",
	["Tupsimati"]="Omniscience",
	["Idris"]="Exudation",
	["Epeolatry"]="Dimidiation",
	--empyrean
	["Verethragna"]="Victory Smite",
	["Twashtar"]="Rudra's Storm",
	["Almace"]="Chant du Cygne",
	["Caladbolg"]="Torcleaver",
	["Farsha"]="Cloudsplitter",
	["Ukonvasara"]="Ukko's Fury",
	["Redemption"]="Quietus",
	["Rhongomiant"]="Camlann's Torment",
	["Kannagi"]="Blade: Hi",
	["Masamune"]="Tachi: Fudo",
	["Gambanteinn"]="Dagan",
	["Hvergelmir"]="Myrkr",
	["Gandiva"]="Jishnu's Radiance",
	["Armageddon"]="Wildfire",
}